version: '2.4'

services:
  registry:
    restart: always
    image: registry
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true 
    volumes:
      - ./test/registry/:/var/lib/registry
