name: Continuous Integration
on: 
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }} 
    - name: event_name
      run: echo ${{ github.event_name }} 
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.1']
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: report gemfile name ruby ${{ matrix.ruby-version }}
      run: make gem
